services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - merchant-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  gateway-postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${GATEWAY_POSTGRES_DB:-paymenti7_gateway}
      POSTGRES_USER: ${GATEWAY_POSTGRES_USER:-paymenti7}
      POSTGRES_PASSWORD: ${GATEWAY_POSTGRES_PASSWORD:-paymenti7}
    ports:
      - "${GATEWAY_POSTGRES_PORT:-5433}:5432"
    volumes:
      - payment-gateway-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  authorization-postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${AUTHORIZATION_POSTGRES_DB:-paymenti7_authorization}
      POSTGRES_USER: ${AUTHORIZATION_POSTGRES_USER:-paymenti7}
      POSTGRES_PASSWORD: ${AUTHORIZATION_POSTGRES_PASSWORD:-paymenti7}
    ports:
      - "${AUTHORIZATION_POSTGRES_PORT:-5434}:5432"
    volumes:
      - payment-authorization-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4.3.5-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - merchant-rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.4-alpine
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - payment-gateway-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  merchant-postgres-data:
  payment-gateway-postgres-data:
  payment-authorization-postgres-data:
  merchant-rabbitmq-data:
  payment-gateway-redis-data:
