spring.application.name=payment-gateway-core
spring.config.import=optional:file:.env[.properties]

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:paymenti7}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:paymenti7}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:/}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

management.endpoints.access.default=none
management.endpoint.health.access=read-only
